version: "3.8"

services:
  whatsapp-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: whatsapp-api:latest
    container_name: whatsapp-api
    ports:
      - "${PORT}:8000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
    restart: always
